title: PiGig GadgetPulse

email: your-email@example.com
description: >- 
  Reviews and recommendations for top tech gadgets.
baseurl: "/my-affiliate-blog" 
url: "https://pigig-gk.github.io" 
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
