email: pi.gigworker@proton.me
description: >-
  Reviews and recommendations for top tech gadgets.
baseurl: "/gadgetpulse"
url: "https://pigig-gk.github.io"
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown

header_pages:
  - index.md
  - _pages/usb-fans.md
