title: GadgetPulse by PiGig

email: your-email@example.com
description: >- 
  Reviews and recommendations for top tech gadgets.
baseurl: "/my-affiliate-blog" 
url: "https://gadgetpulse.github.io" 
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
