title: GadgetPulse by PiGig
email: your-email@example.com
description: >-
  Reviews and recommendations for top tech gadgets.
baseurl: "/gadgetpulse"
url: "https://pigig-gk.github.io"
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
